### ISSUE TITLE
Flashing .bin files fails on dwm1001

### ISSUE THREAD

**Issue by rdagher** [iot-lab/iot-lab-gateway#136] opened 2021-01-27 10:02 UTC
Hello,

I have tried flashing decawave's factory [image](https://www.decawave.com/dwm1001-dw10001-dev-and-mdek1001-documents-source-code-android-application-firmware-image/) into the dwm1001 nodes. Since the firmware is provided in hex format, I first converted it to binary as follows:
```haskell
$ arm-none-eabi-objcopy -I ihex -O binary DWM1001_PANS_R2.0.hex DWM1001_PANS_R2.bin
```

Of course, I first flashed the bin file locally on a dwm1001-dev board to check the conversion (you never now), and it works as expected:
- Connect to the serial interface with 115200 bauds
- Type enter twice to get the prompt `dwm>`, and type the `si` command that display the system's information like this:
```shell
DWM1001 TWR Real Time Location System

 Copyright :  2016-2019 LEAPS and Decawave
 License   :  Please visit https://decawave.com/dwm1001_license
 Compiled  :  Mar 27 2019 03:35:59

 Help      :  ? or help

dwm> si
[000030.370 INF] sys: fw2 fw_ver=x01030001 cfg_ver=x00010700
[000030.370 INF] uwb0: panid=x0000 addr=xDECA2A43BCC2DC90
[000030.380 INF] mode: tn (pasv,twr,np,le)
[000030.380 INF] uwbmac: disconnected
[000030.380 INF] uwbmac: bh disconnected
[000030.390 INF] cfg: sync=0 fwup=0 ble=1 leds=1 le=1 lp=0 stat_det=1 (sens=1) mode=0 upd_rate_norm=1 upd_rate_stat=100 label=DWDC90
[000030.400 INF] enc: off
[000030.400 INF] ble: addr=CF:9A:25:1A:A0:B4
dwm> 
```

Then, I uploaded it into my account and submitted an experiment. Once the experiment is submitted, I get the following error:

![Screenshot](https://user-images.githubusercontent.com/11162310/105974184-690b1300-606c-11eb-959a-5c20ced4584c.png)

Cheers,
Roudy

**Comment by aabadie** [comment] 2021-01-28 08:44
It seems that you set the firmware during the experiment submit and the submit failed. Can you try to submit an experiment with a firmware and flash the firmware once the experiment is running (and successful) ? Use `iotlab-node --flash <firmware.bin>`. By default, this command will flash all boards in your experiment.

**Comment by rdagher** [comment] 2021-02-16 15:30
@aabadie It works as you suggest. Firmware is flashed via the CLI. 
Nevertheless, when connected to the terminal (on the portal or over netcat), the firmware expects typing enter twice to enter in shell mode (from firmware's doc): 
> The Shell mode can be switched to by pressing ENTER twice within 1 second.

This is currently not working, maybe due to `socat` args during serial redirection to tcp.
As a result, such way of operations seems inachievable !

**Comment by aabadie** [comment] 2021-02-16 15:43
Really strange, socat is configured in raw mode, without echo. Can you eventually try via the websocket client (from the webportal or using iotlabwscli) ?

**Comment by rdagher** [comment] 2021-02-16 16:15
From the webportal the same. I will try with iotlabwscli. Attached the bin file if you want to give it a try. Remove the .txt extension, just added it to let it pass through github.
[DWM1001_PANS_R2.bin.txt](https://github.com/iot-lab/iot-lab-gateway/files/5989976/DWM1001_PANS_R2.bin.txt)

**Comment by rdagher** [comment] 2021-02-17 09:27
similar behaviour with iotlabwscli.
```shell
$ python3 -c "from iotlabwscli.parser import main; main()" --verbose
```

**Comment by rdagher** [comment] 2021-02-17 13:10
I reproduced the issue locally by plugging a dwm1001-dev on a linux machine and running socat:
```shell
$ socat -d TCP4-LISTEN:20000,reuseaddr open:/dev/ttyACM0,ispeed=155200,ospeed=115200,echo=0,raw
```
then 
```
$ nc localhost 20000
```
Typing enter twice does not work as when doing so on the serial port `/dev/ttyACM0` directly.

On the other hand, doing the following, switches the firmware to shell mode:
```shell
$ echo -n -e '\r\r' | nc localhost 20000
```
Note that replacing the sequence `\r\r`by `\n\n` does not work. Conclusion, i suspect that when typing enter twice, we are sending `\r\n\r\n` !

**Comment by rdagher** [comment] 2021-02-17 13:32
So, as a workaround, I managed to enter the shell mode by running the command on my node
```shell
$ echo -n -e '\r\r' | nc dwm1001-1 20000
```
Once it enters in shell mode, i have the shell working on the webportal and locally.
[
![shell-mode-fit](https://user-images.githubusercontent.com/11162310/108211184-2ab4c100-710b-11eb-99b8-b9dfd588ad7a.png)
](url)

**Comment by aabadie** [comment] 2021-02-17 15:38
So the issue is more on the client side and not in the gateway code side. Good to know that you could find a workaround (this one was hard to find!).
Do you think we can close this issue ?

**Comment by rdagher** [comment] 2021-02-17 15:56
Yes, it's client-side issue, so this one can be closed. 
Thanks for your help !

**Closed as completed** 2021-02-17 15:57 UTC
